library(shiny)
library(shinydashboard)
library(haven)
library(survival)
library(survminer)
library(rpact)
library(DT)
library(ggplot2)
library(plotly)

# M4: Event Projection dependencies (loaded lazily inside the module if available)
# install.packages(c("eventTrack", "fitdistrplus"))

source("R/utils_data.R")
source("R/utils_compare.R")
source("R/utils_pfs_derive.R")
source("R/utils_report.R")
source("R/mod_ia_boundary.R")
source("R/mod_sample_size.R")
